"""
Generate dashboard/public/data/neighborhood_business_enriched.geojson

Aggregates LA business license data by LA Times neighborhood and crosses
with existing crime data. Only the output (~300 KB) goes to GitHub.

Sources (local, never pushed):
  businesses.parquet                          (generated by csv_to_parquet_businesses.py)
  dashboard/public/data/neighborhood_crimes.geojson

Run from repo root:
    python scripts/generate_business_data.py
"""

import json, re
import numpy as np
import pandas as pd
import geopandas as gpd
from pathlib import Path
from shapely.geometry import Point

ROOT     = Path(__file__).parent.parent
PARQUET  = Path(r"C:\Users\corra\Desktop\POWER BI Proyectos\L.APD crimes\Listing_of_All_Businesses_20260606\businesses.parquet")
NB_FILE  = ROOT / "dashboard/public/data/neighborhood_crimes.geojson"
OUT      = ROOT / "dashboard/public/data/neighborhood_business_enriched.geojson"

# ── NAICS sector mapping (simplified) ─────────────────────────────────────
SECTORS = {
    "Food & Restaurants":    ["restaurant", "food", "beverage", "bar ", "cafe", "bakery", "catering"],
    "Retail":                ["retail", "store", "shop", "market", "dealer", "clothing", "furniture"],
    "Real Estate":           ["real estate", "lessor", "property management", "apartment"],
    "Professional Services": ["consulting", "professional", "scientific", "technical", "legal", "accounting"],
    "Construction":          ["construction", "contractor", "builder", "electrician", "plumb"],
    "Entertainment":         ["motion picture", "video", "artist", "performer", "music", "theater", "sport"],
    "Personal Services":     ["personal service", "beauty", "barber", "laundry", "repair", "auto"],
    "Health":                ["health", "medical", "dental", "hospital", "physician", "nurse", "pharmacy"],
    "Education":             ["school", "education", "tutor", "child care", "daycare"],
}

def assign_sector(desc):
    if pd.isna(desc): return "Other"
    d = str(desc).lower()
    for sector, keywords in SECTORS.items():
        if any(k in d for k in keywords):
            return sector
    return "Other"

# ── 1. Load and filter businesses ─────────────────────────────────────────
print("Loading business data...")
df = pd.read_parquet(PARQUET, columns=[
    "location", "primary_naics_description", "location_end_date",
    "council_district", "location_start_date"
])
print(f"  {len(df):,} total records")

# Active businesses only (no end date)
active = df[df["location_end_date"].isna()].copy()
print(f"  {len(active):,} active businesses")

# Parse location "(lat, lon)" — keep only valid LA coords
def parse_loc(s):
    if pd.isna(s): return None, None
    m = re.search(r'\(\s*([-\d.]+)\s*,\s*([-\d.]+)\s*\)', str(s))
    if not m: return None, None
    lat, lon = float(m.group(1)), float(m.group(2))
    return lat, lon

print("Parsing coordinates...")
coords = active["location"].apply(parse_loc)
active["lat"] = coords.apply(lambda x: x[0])
active["lon"] = coords.apply(lambda x: x[1])

# Valid: lon is negative (CA) and lat in rough LA County bbox
valid = active[
    active["lon"].notna() &
    (active["lon"] < -100) &
    active["lat"].between(33.5, 34.6)
].copy()
print(f"  {len(valid):,} active businesses with valid LA coordinates")

# Assign sector
valid["sector"] = valid["primary_naics_description"].apply(assign_sector)

# ── 2. Load neighborhoods ──────────────────────────────────────────────────
print("Loading neighborhoods...")
nb = gpd.read_file(NB_FILE)
print(f"  {len(nb)} neighborhoods")

# ── 3. Spatial join: businesses -> neighborhoods ───────────────────────────
print("Spatial join (businesses -> neighborhoods)...")
biz_gdf = gpd.GeoDataFrame(
    valid,
    geometry=[Point(lon, lat) for lat, lon in zip(valid["lat"], valid["lon"])],
    crs=4326
)

joined = gpd.sjoin(biz_gdf[["geometry","sector"]], nb[["geometry","name"]], how="left", predicate="within")
print(f"  {joined['name'].notna().sum():,} businesses matched to a neighborhood")

# ── 4. Aggregate by neighborhood ───────────────────────────────────────────
print("Aggregating...")

# Total active businesses per neighborhood
counts = joined.groupby("name").size().reset_index(name="biz_count")

# Count per sector
sector_counts = joined.groupby(["name","sector"]).size().unstack(fill_value=0).reset_index()

# Top sector per neighborhood
joined_nn = joined.dropna(subset=["name"])
top_sector = joined_nn.groupby("name")["sector"].agg(
    lambda x: x.value_counts().index[0] if len(x) > 0 else "Other"
).reset_index().rename(columns={"sector": "top_sector"})

# ── 5. Merge with neighborhood crime GeoDataFrame ─────────────────────────
result = nb.merge(counts,      on="name", how="left")
result = result.merge(top_sector, on="name", how="left")

# Add per-sector columns (use lowercase column names from unstack)
sector_cols = [c for c in sector_counts.columns if c != "name"]
result = result.merge(sector_counts[["name"] + sector_cols], on="name", how="left")
for sc in sector_cols:
    if sc in result.columns:
        result[sc] = result[sc].fillna(0).astype(int)
        # Rename to snake_case prefixed
        safe = "biz_" + sc.lower().replace(" & ", "_").replace(" ", "_").replace("/", "_")
        result.rename(columns={sc: safe}, inplace=True)

result["biz_count"] = result["biz_count"].fillna(0).astype(int)
result["top_sector"] = result["top_sector"].fillna("N/A")

# ── 6. Derived metrics ─────────────────────────────────────────────────────
# Businesses per 1,000 inhabitants
result["biz_per_1000"] = np.where(
    result["population"] > 0,
    (result["biz_count"] / (result["population"] / 1000)).round(1),
    0
)

# Crimes per business (commercial crime intensity)
result["crimes_per_biz"] = np.where(
    result["biz_count"] > 0,
    (result["crime_count"] / result["biz_count"]).round(2),
    None
)

# Normalize for choropleth
cap_biz  = result["biz_count"].quantile(0.98)
cap_rate = result.loc[result["biz_per_1000"] > 0, "biz_per_1000"].quantile(0.98)
cap_cpb  = result.loc[result["crimes_per_biz"].notna(), "crimes_per_biz"].quantile(0.98)
result["norm_biz_count"]  = (result["biz_count"]   / cap_biz).clip(0,1).round(4)
result["norm_biz_rate"]   = (result["biz_per_1000"] / cap_rate).clip(0,1).round(4)
result["norm_crimes_pbiz"]= (result["crimes_per_biz"].fillna(0) / cap_cpb).clip(0,1).round(4)

# Business rank
result = result.sort_values("biz_count", ascending=False).reset_index(drop=True)
result["biz_rank"] = result.index + 1

# Round display fields
result["biz_per_1000"]  = result["biz_per_1000"].round(1)
result["crimes_per_biz"]= result["crimes_per_biz"].round(2)

# ── 7. Write GeoJSON ───────────────────────────────────────────────────────
OUT.parent.mkdir(parents=True, exist_ok=True)
result.to_file(OUT, driver="GeoJSON")

size_kb = OUT.stat().st_size / 1024
print(f"\nDone -> {OUT.name}  ({size_kb:.0f} KB)")
print(f"  neighborhoods: {len(result)}")
print(f"  total active businesses mapped: {result['biz_count'].sum():,}")

print(f"\nTop 10 neighborhoods by business count:")
for _, row in result.head(10).iterrows():
    cpb = f"{row['crimes_per_biz']:.1f}" if row['crimes_per_biz'] else "N/A"
    print(f"  {row['biz_rank']:2}. {row['name']:<28} {row['biz_count']:>6,} bizs  "
          f"{row['biz_per_1000']:>5.0f}/1k  {cpb} crimes/biz  top:{row['top_sector']}")
